### ISSUE TITLE
Improper calculation

### ISSUE THREAD

**Issue by Mujammil-ios** [sailab-banik/Math-Expression-Scanner#2]
When we capture an image from the app it does not calculate properly sometimes it does not capture the image properly and if capture it will show the wrong calculation. **It can happen if you already know this problem.**
> In this application you used awesome logic.
Thank you.

**Comment by sailab-banik** [comment]
Thank you for your comment.
I have used ML Kit Text Recognition in this Project, it only detects the Latin Script and not build for Handwriting Recognition.  I have made this project for learning Purpose. Thank You.
